version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - appspec.yaml
    - buildspec.yaml